Repository substrait-io/substrait, pull requests merged in 2023-07, with the labels that each got.

#518 feat: add ExchangeRel as a type in Rel
  proto/substrait/algebra.proto
Labels: awaiting PMC approval

#508 feat: add options to substring for start parameter being negative
  extensions/functions_string.yaml
Labels: extension

#499 build: update buf plugin references in buf.gen.yaml
  buf.gen.yaml
Labels: protobuf
